Repository moonshotcollective/anonvsmoloch-NFT, pull requests merged in 2021-09, with the labels that each got.

#20 Issue 22
  packages/hardhat/contracts/YourCollectible.sol
  packages/hardhat/scripts/mint.js
  packages/react-app/package.json
  packages/react-app/src/App.jsx
  packages/react-app/src/components/Address.jsx
  packages/react-app/src/components/Faucet.jsx
  packages/react-app/src/components/Header.jsx
  packages/react-app/src/components/Swap.jsx
  packages/react-app/src/components/ThemeSwitch.jsx
  packages/react-app/src/components/index.js
  packages/react-app/src/hooks/Balance.js
  packages/react-app/src/hooks/BurnerSigner.js
  packages/react-app/src/hooks/ContractLoader.js
  packages/react-app/src/hooks/Debounce.js
  packages/react-app/src/hooks/GasPrice.js
  packages/react-app/src/hooks/IpfsStorage.js
  packages/react-app/src/hooks/OnBlock.js
  packages/react-app/src/hooks/Poller.js
  packages/react-app/src/hooks/TokenList.js
  packages/react-app/src/hooks/index.js
  packages/react-app/src/index.jsx
  packages/react-app/src/views/Store.jsx
  yarn.lock
Labels: clean-up, front-end, housekeeping

#23 Issue-17: Added sandwhich navigation page
  packages/react-app/package.json
  packages/react-app/src/App.css
  packages/react-app/src/App.jsx
  packages/react-app/src/assets/burgerMenuIcon.svg
  packages/react-app/src/assets/intro-background.png
  yarn.lock
Labels: front-end

#26 remove faucet add store code
  packages/hardhat/contracts/YourCollectible.sol
  packages/hardhat/test/mintNFT.test.js
  packages/hardhat/test/myTest.js
  packages/react-app/src/App.jsx
  packages/react-app/src/components/Faucet.jsx
  packages/react-app/src/components/index.js
  packages/react-app/src/views/Gallery.jsx
  packages/react-app/src/views/Store.jsx
  packages/react-app/src/views/index.js
Labels: clean-up, front-end, housekeeping

#25 Added Site FAQ
  packages/react-app/craco.config.js
  packages/react-app/eslintrc.json
  packages/react-app/package.json
  packages/react-app/src/App.css
  packages/react-app/src/App.jsx
  packages/react-app/src/assets/icon-discord.svg
  packages/react-app/src/assets/icon-mail.svg
  packages/react-app/src/assets/icon-twitter.svg
  packages/react-app/src/assets/icon-youtube.svg
  packages/react-app/src/assets/panel-arrow-down.svg
  packages/react-app/src/assets/panel-arrow-up.svg
  packages/react-app/src/components/Faq/ArrowButton.jsx
  packages/react-app/src/components/Faq/Faq.css
  packages/react-app/src/components/Faq/index.jsx
  packages/react-app/src/components/Footer/Footer.css
  packages/react-app/src/components/Footer/index.js
  packages/react-app/src/components/index.js
  packages/react-app/src/index.css
  packages/react-app/tailwind.config.js
  yarn.lock
Labels: front-end, back-end
